server:
  port: 8081

spring:
  application:
    name: Hotel-Service
  datasource:
    url: ${POSTGRESQL_URL}
    username: ${POSTGRESQL_USERNAME}
    password: ${POSTGRESQL_PASSWORD}

  jpa:
    hibernate:
      ddl-auto:update
    show-sql: true
  config:
    import: optional:file:.env
