server:
  port: 8081

spring:
  application:
    name: Hotel-Service
  datasource:
    url: ${POSTGRESQL_URL}
    username: ${POSTGRESQL_USERNAME}
    password: ${POSTGRESQL_PASSWORD}
    hikari:
      max-lifetime: 60000
      idle-timeout: 30000
      connection-timeout: 20000

  jpa:
    hibernate:
      ddl-auto:update
  config:
    import: optional:file:.env[.properties]
