spring:
  application:
    name: Haven-Gateway
  cloud:
    gateway:
      server:
        webflux:
          globalcors:
            cors-configurations:
              '[/**]':
                allowedOrigins: "http://localhost:3000"
                allowedMethods:
                  - GET
                  - POST
                  - PUT
                  - DELETE
                  - OPTIONS
                allowedHeaders: "*"
                allowCredentials: true
                maxAge: 3600
          routes:

            - id: hotel-service-public
              uri: http://localhost:8081/
              predicates:
                - Path=/api/v1/public/hotel/**

            - id: hotel-service-protected
              uri: http://localhost:8081/
              predicates:
                - Path=/api/v1/protected/hotel/**

            - id: auth-service-public
              uri: http://localhost:8082/
              predicates:
                - path=/api/v1/public/auth/**

            - id: auth-service-protected
              uri: http://localhost:8082/
              predicates:
                - path=/api/v1/protected/auth/**

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:9000/oauth2/jwks
          issuer-uri: http://localhost:9000
server:
  port: 8080
