spring.application.name=Haven-Gateway

server.port=8080

# Hotel service
spring.cloud.gateway.routes[0].id=hotel-service
spring.cloud.gateway.routes[0].uri=http://localhost:8081/
spring.cloud.gateway.routes[0].predication[0]=path=/api/hotels/**